// src/components/admin/StudentManager.tsx
import React, { useState } from 'react'
import ExcelUploader from './ExcelUploader'
import {
  createEstudiante,
  uploadEstudiantesExcel,
  getEstudiantes,
  toggleStudentState, // Import the toggle function
  updateEstudiante, // Import the update function
} from '@/Functions/studentsApi'

interface Student {
  id: string;
  carnet: string;
  cedula: string;
  nombre: string;
  apellidos: string; // Added field for last name
  nombre_completo: string; // Concatenation of `nombre` and `apellidos`
  correo: string;
  telefono: string; // Updated format to exclude hyphen
  password?: string; // Added field for autogenerated password
  isAdmin?: boolean; // Always false
  estado?: string; // Always "activo"
}

const StudentManager: React.FC<{ reloadKey?: number }> = ({ reloadKey }) => {
  const [students, setStudents] = useState<Student[]>([])
  const [selectedFile, setSelectedFile] = useState<File | null>(null)
  const [newStud, setNewStud] = useState<Omit<Student, 'id' | 'password' | 'isAdmin' | 'estado' | 'nombre_completo'>>({
    carnet: '',
    cedula: '',
    nombre: '',
    apellidos: '', // Added field for last name
    correo: '',
    telefono: '',
  })
  const [loading, setLoading] = useState(true)
  const [editingIndex, setEditingIndex] = useState<number | null>(null)
  const [editingStudent, setEditingStudent] = useState<Student | null>(null)

  // Expresiones regulares de validación
  const carnetRegex  = /^20\d{8}$/
  const cedulaRegex  = /^\d{9}$/
  const telefonoRegex = /^\d{4}-\d{4}$/

  // Referencia al archivo Excel
  const handleFileSelect = (file: File) => setSelectedFile(file)

  // Confirmar importación desde Excel
  const confirmImport = async () => {
    if (!selectedFile) {
      alert('No hay archivo seleccionado.')
      return
    }
    try {
      await uploadEstudiantesExcel(selectedFile)
      alert('Archivo enviado al servidor para procesamiento.')
      setSelectedFile(null)
      // Opcional: recargar lista de estudiantes desde el backend aquí
    } catch (err) {
      alert('Error al subir el archivo.')
    }
  }

  // Manejo de formulario manual
  const handleManualChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target
    setNewStud(s => ({ ...s, [name]: value }))
  }

  const addManual = async () => {
    const { carnet, cedula, nombre, apellidos, correo, telefono } = newStud;
    // Campos obligatorios
    if (!carnet || !cedula || !nombre || !apellidos || !correo || !telefono) {
      alert('Todos los campos son obligatorios.')
      return
    }
    // Formatos correctos
    if (!carnetRegex.test(carnet)) {
      alert('Carné inválido: debe empezar con "20" y tener 10 dígitos.')
      return
    }
    if (!cedulaRegex.test(cedula)) {
      alert('Cédula inválida: debe tener 9 dígitos.')
      return
    }
    if (!/^\d{8}$/.test(telefono)) {
      alert('Teléfono inválido: formato debe ser 8 dígitos sin guion.')
      return
    }
    // No duplicados
    if (
      students.some(s => s.carnet === carnet) ||
      students.some(s => s.cedula === cedula)
    ) {
      alert('Ya existe un estudiante con ese carné o cédula.')
      return
    }

    try {
      const password = Math.random().toString(36).slice(-8); // Autogenerate password
      const newStudent = {
        carnet,
        cedula,
        nombre,
        apellidos,
        nombre_completo: `${nombre} ${apellidos}`, // Concatenate name and last name
        correo: correo,
        telefono,
        password,
        isAdmin: false,
        estado: 'activo',
      };
      const result = await createEstudiante(newStudent);
      const entry: Student = {
        id: result.id,
        carnet,
        cedula,
        nombre,
        apellidos,
        nombre_completo: `${nombre} ${apellidos}`,
        correo,
        telefono,
      };
      setStudents(prev => [...prev, entry]);
      setNewStud({ carnet: '', cedula: '', nombre: '', apellidos: '', correo: '', telefono: '' })
      alert(`Estudiante agregado correctamente.\nContraseña: ${password}`)
    } catch (err) {
      alert('Error al agregar estudiante.')
    }
  }

  const handleEdit = (idx: number) => {
    setEditingIndex(idx);
    setEditingStudent({ ...students[idx] });
  };

  const saveEdit = async () => {
    if (editingIndex === null || !editingStudent) return;
    try {
      await updateEstudiante(editingStudent.id, {
        id: editingStudent.id,
        carnet: editingStudent.carnet,
        cedula: editingStudent.cedula,
        nombre: editingStudent.nombre,
        apellidos: editingStudent.apellidos,
        nombre_completo: `${editingStudent.nombre} ${editingStudent.apellidos}`,
        correo: editingStudent.correo,
        telefono: editingStudent.telefono,
        estado: editingStudent.estado,
        password: "",
      });
      const updatedStudents = await getEstudiantes();
      setStudents(
        updatedStudents.map((s: Student) => ({
          id: s.id,
          carnet: s.carnet,
          cedula: s.cedula,
          nombre: s.nombre,
          apellidos: s.apellidos,
          nombre_completo: s.nombre_completo,
          correo: s.correo,
          telefono: s.telefono,
          estado: s.estado,
        }))
      );
      setEditingIndex(null);
      setEditingStudent(null);
    } catch (error: any) {
      if (error.response?.status === 404) {
        alert('Error: No se encontró el estudiante en el sistema.');
        setEditingIndex(null);
        setEditingStudent(null);
        const updatedStudents = await getEstudiantes();
        setStudents(
          updatedStudents.map((s: Student) => ({
            id: s.id,
            carnet: s.carnet,
            cedula: s.cedula,
            nombre: s.nombre,
            apellidos: s.apellidos,
            nombre_completo: s.nombre_completo,
            correo: s.correo,
            telefono: s.telefono,
            estado: s.estado,
          }))
        );
      } else {
        alert('Error al editar estudiante.');
      }
    }
  };

  const cancelEdit = () => {
    setEditingIndex(null);
    setEditingStudent(null);
  };

  const toggleDisabled = async (idx: number) => {
    const student = students[idx];
    if (!student.id) return;
    try {
      await toggleStudentState(student.id); // Assume toggleStudentState exists in studentsApi
      const updatedStudents = await getEstudiantes();
      setStudents(
        updatedStudents.map((s: Student) => ({
          id: s.id,
          carnet: s.carnet,
          cedula: s.cedula,
          nombre: s.nombre,
          apellidos: s.apellidos,
          nombre_completo: s.nombre_completo,
          correo: s.correo,
          telefono: s.telefono,
          estado: s.estado,
        }))
      );
    } catch {
      alert('Error al cambiar estado del estudiante.');
    }
  };

  React.useEffect(() => {
    setLoading(true);
    getEstudiantes()
      .then((data: Student[]) => {
        setStudents(
          data.map((s: Student) => ({
            id: s.id,
            carnet: s.carnet,
            cedula: s.cedula,
            nombre: s.nombre,
            apellidos: s.apellidos,
            nombre_completo: s.nombre_completo,
            correo: s.correo, // Map `correo` to `correo`
            telefono: s.telefono,
            estado: s.estado,
          }))
        );
      })
      .catch(() => setStudents([]))
      .finally(() => setLoading(false));
  }, [reloadKey])

  return (
    <div>
      <h2 className="mb-4">Gestión de Estudiantes</h2>

      {/* Agregar Estudiante Manualmente */}
      <div className="mb-4 p-3" style={{ border: '1px solid #ddd', borderRadius: 6 }}>
        <h5>Agregar Estudiante Manualmente</h5>
        <div className="row g-2">
          <div className="col">
            <input
              name="carnet"
              value={newStud.carnet}
              onChange={handleManualChange}
              placeholder="Carné (2020XXXXXX)"
              className="form-control"
            />
          </div>
          <div className="col">
            <input
              name="cedula"
              value={newStud.cedula}
              onChange={handleManualChange}
              placeholder="Cédula (9 dígitos)"
              className="form-control"
            />
          </div>
          <div className="col">
            <input
              name="nombre"
              value={newStud.nombre}
              onChange={handleManualChange}
              placeholder="Nombre"
              className="form-control"
            />
          </div>
          <div className="col">
            <input
              name="apellidos"
              value={newStud.apellidos}
              onChange={handleManualChange}
              placeholder="Apellidos"
              className="form-control"
            />
          </div>
          <div className="col">
            <input
              name="correo"
              value={newStud.correo}
              onChange={handleManualChange}
              placeholder="Correo electrónico"
              className="form-control"
            />
          </div>
          <div className="col">
            <input
              name="telefono"
              value={newStud.telefono}
              onChange={handleManualChange}
              placeholder="Teléfono (88880000)"
              className="form-control"
            />
          </div>
          <div className="col-auto">
            <button className="btn btn-primary" onClick={addManual}>
              Agregar
            </button>
          </div>
        </div>
      </div>

      {/* Temporarily disabled Excel import
      <div className="mb-4">
        <h5>Importar desde Excel</h5>
        <ExcelUploader onFileSelect={handleFileSelect} />
        {selectedFile && (
          <div className="mt-2">
            <span>Archivo listo: {selectedFile.name}</span>{' '}
            <button className="btn btn-success btn-sm ms-2" onClick={confirmImport}>
              Confirmar importación
            </button>
          </div>
        )}
      </div>
      */}

      {/* Tabla de Estudiantes */}
      <table className="table table-striped">
        <thead>
          <tr>
            <th>Carné</th>
            <th>Cédula</th>
            <th>Nombre</th>
            <th>Apellidos</th>
            <th>Email</th>
            <th>Teléfono</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          {loading ? (
            <tr>
              <td colSpan={7} className="text-center text-muted">
                Cargando...
              </td>
            </tr>
          ) : students.length > 0 ? (
            students.map((s, i) => (
              <tr key={s.id} className={s.estado === 'inactivo' ? 'opacity-50' : ''}>
                <td>{s.carnet}</td>
                <td>{s.cedula}</td>
                <td>{s.nombre}</td>
                <td>{s.apellidos}</td>
                <td>{s.correo}</td>
                <td>{s.telefono}</td>
                <td>
                  <button
                    className="btn btn-sm btn-primary me-1"
                    onClick={() => handleEdit(i)}
                  >
                    Editar
                  </button>
                  <button
                    className={`btn btn-sm ${s.estado === 'inactivo' ? 'btn-success' : 'btn-danger'}`}
                    onClick={() => toggleDisabled(i)}
                  >
                    {s.estado === 'inactivo' ? 'Habilitar' : 'Deshabilitar'}
                  </button>
                </td>
              </tr>
            ))
          ) : (
            <tr>
              <td colSpan={7} className="text-center text-muted">
                Sin estudiantes
              </td>
            </tr>
          )}
        </tbody>
      </table>

      {/* Editar Estudiante - Modal */}
      {editingIndex !== null && editingStudent && (
        <div style={overlayStyle}>
          <div style={modalStyle}>
            <div className="d-flex justify-content-between align-items-center mb-3">
              <h5>Editar Estudiante</h5>
              <button className="btn btn-sm btn-secondary" onClick={cancelEdit}>
                X
              </button>
            </div>

            <div className="mb-3">
              <label className="form-label">Carné</label>
              <input
                type="text"
                className="form-control"
                value={editingStudent.carnet}
                onChange={(e) => setEditingStudent({ ...editingStudent, carnet: e.target.value })}
              />
            </div>
            <div className="mb-3">
              <label className="form-label">Cédula</label>
              <input
                type="text"
                className="form-control"
                value={editingStudent.cedula}
                onChange={(e) => setEditingStudent({ ...editingStudent, cedula: e.target.value })}
              />
            </div>
            <div className="mb-3">
              <label className="form-label">Nombre</label>
              <input
                type="text"
                className="form-control"
                value={editingStudent.nombre}
                onChange={(e) => setEditingStudent({ ...editingStudent, nombre: e.target.value })}
              />
            </div>
            <div className="mb-3">
              <label className="form-label">Apellidos</label>
              <input
                type="text"
                className="form-control"
                value={editingStudent.apellidos}
                onChange={(e) => setEditingStudent({ ...editingStudent, apellidos: e.target.value })}
              />
            </div>
            <div className="mb-3">
              <label className="form-label">Correo</label>
              <input
                type="email"
                className="form-control"
                value={editingStudent.correo}
                onChange={(e) => setEditingStudent({ ...editingStudent, correo: e.target.value })}
              />
            </div>
            <div className="mb-3">
              <label className="form-label">Teléfono</label>
              <input
                type="text"
                className="form-control"
                value={editingStudent.telefono}
                onChange={(e) => setEditingStudent({ ...editingStudent, telefono: e.target.value })}
              />
            </div>

            <div className="d-flex justify-content-end mt-4">
              <button className="btn btn-secondary me-2" onClick={cancelEdit}>
                Cancelar
              </button>
              <button className="btn btn-primary" onClick={saveEdit}>
                Guardar cambios
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

export default StudentManager

const overlayStyle: React.CSSProperties = {
  position: 'fixed',
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  backgroundColor: 'rgba(0, 0, 0, 0.7)',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  zIndex: 1050,
};

const modalStyle: React.CSSProperties = {
  backgroundColor: 'white',
  padding: '2rem',
  borderRadius: '0.5rem',
  boxShadow: '0 4px 8px rgba(0, 0, 0, 0.2)',
  minWidth: '300px',
  maxWidth: '500px',
  width: '100%',
};
